### ISSUE TITLE
Send Mincoin Screen /Add Newest  RecTx addresses to be selected  without label\

### ISSUE THREAD

**Issue by ghost** [gotaproblem/dev-mincoin#1]
In Send Mincoin Screen; allow user to select any recent sending wallet.

Removing the necessity for a label on sending address, the user will be able to make transactions faster and prevent their address book from being cluttered from 1x transactions

Currently the user must type the first letter into the text  field for a drop down menu to appear listing the contact.

If a drop down of  the most recent TX address's appeared when you pressed the text input field, it would be much more fluid for temporary or short time users to conduct transactions.

**Comment by gotaproblem** [comment]
In this version of the app, this will not change.
